name: JB
title: Record electric guitar on PC
description: An easy guide for home recording
remote_theme: KomunikacjaTechnicznaVistula/just-the-docs

color_scheme: test_jbuk

#logo: "/assets/images/vumeter1.png"

aux_links:
  "Source repository on GitHub":
    - "https://github.com/JakubBuk/RecordGuitar"

back_to_top: true
back_to_top_text: "Back to top"

